/**
 * gen-icons.js — Generates frontend/assets/vendor/icons.js
 *
 * Celso POS uses ~40 icons but historically shipped the full 265 KB Lucide
 * runtime (1,200+ icons) on EVERY page, render-blocking in <head>. That hurts
 * our target users most: low-end Android phones on throttled connections.
 *
 * This script reads the icon definitions out of the existing lucide.min.js and
 * emits a tiny (~6 KB) drop-in shim that exposes the SAME public API
 * (window.lucide.createIcons) over an inline subset of only the icons we use —
 * so no HTML/JS call sites change. To add an icon: add its kebab name to
 * USED_ICONS below and re-run `node scripts/gen-icons.js`.
 *
 * The output is generated — do not hand-edit assets/vendor/icons.js.
 */
'use strict';

const fs = require('fs');
const path = require('path');

// Every data-lucide name the app references — static markup AND the handful
// built dynamically in JS (sidebar links, theme toggle, team toggles, dashboard
// banner). Keep this list in sync if new icons are introduced.
const USED_ICONS = [
  'alert-triangle', 'archive', 'badge-dollar-sign', 'banknote', 'bar-chart-2',
  'calculator', 'calendar', 'chevron-left', 'chevron-right', 'clock',
  'credit-card', 'info', 'key-round', 'landmark', 'layers', 'layout-dashboard',
  'leaf', 'lock', 'log-out', 'moon', 'more-vertical', 'package', 'pencil',
  'percent', 'piggy-bank', 'plus', 'receipt', 'search', 'settings-2', 'shield',
  'shopping-cart', 'sliders-horizontal', 'sparkles', 'sun', 'trash-2',
  'trending-up', 'user', 'user-check', 'user-x', 'users', 'wallet', 'x',
  'x-circle',
];

const VENDOR_DIR = path.join(__dirname, '..', 'frontend', 'assets', 'vendor');
const lucide = require(path.join(VENDOR_DIR, 'lucide.min.js'));

// kebab-case -> PascalCase key used in lucide.icons (e.g. bar-chart-2 -> BarChart2)
function pascal(name) {
  return name.split('-').map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('');
}

// Serialize a lucide icon node's CHILDREN (everything inside <svg>) to markup.
// Node shape: ["svg", attrs, [ ["path", {...}], ["line", {...}], ... ]]
function childrenMarkup(iconNode) {
  const children = iconNode[2] || [];
  return children.map(([tag, attrs]) => {
    const a = Object.keys(attrs)
      .map(k => `${k}="${attrs[k]}"`)
      .join(' ');
    return `<${tag} ${a}/>`;
  }).join('');
}

const icons = {};
const missing = [];
for (const name of USED_ICONS) {
  const node = lucide.icons[pascal(name)];
  if (!node) { missing.push(name); continue; }
  icons[name] = childrenMarkup(node);
}

if (missing.length) {
  console.error('Missing icons in lucide.min.js:', missing.join(', '));
  process.exit(1);
}

const banner =
`/**
 * icons.js — GENERATED by scripts/gen-icons.js. Do not hand-edit.
 *
 * Tiny drop-in replacement for the Lucide runtime: exposes the same
 * window.lucide.createIcons() API over an inline subset of the ${USED_ICONS.length} icons
 * Celso POS actually uses. Replaces the 265 KB lucide.min.js that previously
 * loaded render-blocking on every page. Add icons via the generator, not here.
 */`;

const out = `${banner}
(function (global) {
  'use strict';

  // kebab-name -> inner SVG markup (children of <svg>), copied verbatim from Lucide.
  var ICONS = ${JSON.stringify(icons, null, 2)};

  // Shared <svg> root attributes — identical across all Lucide icons.
  var SVG_ATTRS = 'xmlns="http://www.w3.org/2000/svg" width="24" height="24" ' +
    'viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" ' +
    'stroke-linecap="round" stroke-linejoin="round"';

  function buildSvg(name, sourceEl) {
    var inner = ICONS[name];
    if (inner == null) {
      if (global.console && console.warn) console.warn('[icons] unknown icon: ' + name);
      return null;
    }
    var wrap = document.createElement('div');
    // Setting innerHTML with a <svg> root makes the HTML parser create the
    // correctly-namespaced SVG subtree for us.
    wrap.innerHTML = '<svg ' + SVG_ATTRS + '>' + inner + '</svg>';
    var svg = wrap.firstElementChild;

    // Mirror Lucide: carry the source element's attributes (id, class, etc.)
    // onto the output svg so contextual CSS and getElementById keep working.
    var classes = ['lucide', 'lucide-' + name];
    if (sourceEl && sourceEl.attributes) {
      for (var i = 0; i < sourceEl.attributes.length; i++) {
        var attr = sourceEl.attributes[i];
        if (attr.name === 'data-lucide') continue;        // don't re-tag output
        if (attr.name === 'class') {
          attr.value.split(/\\s+/).forEach(function (c) {
            if (c && c.indexOf('lucide') !== 0) classes.push(c); // drop stale lucide-*
          });
          continue;
        }
        svg.setAttribute(attr.name, attr.value);
      }
    }
    svg.setAttribute('class', classes.join(' '));
    return svg;
  }

  // Replace every [data-lucide] element with its inline SVG. Idempotent: output
  // svgs carry no data-lucide, so repeat calls only touch new icons. The theme
  // toggle deliberately re-sets data-lucide on its svg to force a re-render.
  function createIcons() {
    if (typeof document === 'undefined') return;
    var els = document.querySelectorAll('[data-lucide]');
    for (var i = 0; i < els.length; i++) {
      var el = els[i];
      var svg = buildSvg(el.getAttribute('data-lucide'), el);
      if (svg && el.parentNode) el.parentNode.replaceChild(svg, el);
    }
  }

  global.lucide = { createIcons: createIcons, icons: ICONS };

  // Auto-render any static icons present at parse time (the per-page trailing
  // lucide.createIcons() call remains a harmless no-op / safety net).
  if (typeof document !== 'undefined') {
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', createIcons);
    } else {
      createIcons();
    }
  }
})(typeof window !== 'undefined' ? window : this);
`;

fs.writeFileSync(path.join(VENDOR_DIR, 'icons.js'), out);
const kb = (Buffer.byteLength(out) / 1024).toFixed(1);
console.log(`Wrote frontend/assets/vendor/icons.js (${USED_ICONS.length} icons, ${kb} KB)`);
